[package]
name = "simd-0321-interface"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true }

[lints]
workspace = true
